/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const RecommsLazyRouteImport = createFileRoute('/recomms')()
const IndexLazyRouteImport = createFileRoute('/')()

const RecommsLazyRoute = RecommsLazyRouteImport.update({
  id: '/recomms',
  path: '/recomms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recomms.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/recomms': typeof RecommsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/recomms': typeof RecommsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/recomms': typeof RecommsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recomms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recomms'
  id: '__root__' | '/' | '/recomms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RecommsLazyRoute: typeof RecommsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recomms': {
      id: '/recomms'
      path: '/recomms'
      fullPath: '/recomms'
      preLoaderRoute: typeof RecommsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RecommsLazyRoute: RecommsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
